---
- name: Install utils for test
  hosts: pfservers
  gather_facts: True
  become: True
  collections:
    - inverse_inc.utils

  roles:
    - role: venom
      tags: venom

    - role: psonoci
      tags: psonoci

    - role: mailhog
      tags: mailhog
